version: '3.5'

services:
  chat-server:
    build: .
    container_name: open-360-chat-server
    restart: on-failure
    links:
      - socket-redis
    environment:
      - PORT=4002
    ports:
      - "4002:4002"
    #DEBUG VARIABLES
    #  - "9229:9229"
    #command:
    #  - node
    #  - "--inspect-brk=0.0.0.0"
    #  - "main.js"
    #END OF DEBUG
    networks:
      chat-network:
      socket-network:
      api-network:

  socket-redis:
    image: redis
    container_name: open360-redis-socket
    hostname: open360-redis-socket
    volumes:
      - "/usr/src/open360/socket_data:/data"
      - "/usr/src/open360/redis.conf:/usr/local/etc/redis/redis.conf"
    networks:
      socket-network:

networks:
  socket-network:
  chat-network:
    external: true
    name: "open360-chat-network"
  api-network:
    external: true
    name: "open360-api-network"